package com.pl.shugo.gsolog.domain.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * AI-generated report entity.
 * Stores periodic reports generated by AI helper.
 */
@Table("ai_report_history")
public class AiReport {

    @Id
    private UUID id;
    private UUID userId;
    private LocalDate fromDate;
    private LocalDate toDate;
    private String language;  // "PL" or "EN"
    private String content;
    private Instant createdAt;

    public AiReport() {
    }

    /**
     * Factory method to create a new AI report.
     */
    public static AiReport create(UUID userId, LocalDate fromDate, LocalDate toDate, String language, String content) {
        AiReport report = new AiReport();
        report.userId = userId;
        report.fromDate = fromDate;
        report.toDate = toDate;
        report.language = language;
        report.content = content;
        report.createdAt = Instant.now();
        return report;
    }

    // Getters and setters

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public LocalDate getFromDate() {
        return fromDate;
    }

    public void setFromDate(LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    public LocalDate getToDate() {
        return toDate;
    }

    public void setToDate(LocalDate toDate) {
        this.toDate = toDate;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
